
api_auth_index:
    methods: [GET]
    path: auth
    controller: PhpLab\Bundle\User\Api\Controllers\AuthController::index

api_auth_login:
    path: auth
    methods: [POST]
    controller: PhpLab\Bundle\User\Api\Controllers\AuthController::login
